### ISSUE TITLE
设置后无效?

### ISSUE THREAD

**Issue by TonyJason** [iweizime/StepChanger#1]
7.1.1系统，设置后保存，进入微信查看或者支付宝查看，还是原来的，手机已root

**Comment by iweizime** [comment]
一次改的不要太多，这个跟上次上传的时间和步数有关，你改的太快会被服务器认为是异常。改支付宝之前，最好清空一下缓存。

**Comment by TonyJason** [comment]
ok，我改的数值不算很大，等下再改一改，还有，我手机root了，为什么操作的时候不会自动调出root授权框，需要我手动打开SuperSU之后再操作才会调出授权框

**Comment by iweizime** [comment]
SuperSu授权慢跟这个应用应该没关系吧

**Comment by TonyJason** [comment]
的确，我测试了一下，好些APP申请授权都慢，看来是我手机问题。还有，步数亲测有效，不过得几千几千的加，一天改个几次，轻轻松松霸占封面榜

**Comment by iweizime** [comment]
改的时候会做一个检查，检查增加的步数在上次上传时到现在这段时间内是否合理，现在设置的是每秒最多5步。如果超过每秒5步会提示，选择继续也可以改本地的，但是上传后可能会被服务器认为是异常
