### ISSUE TITLE
支付宝步数加载问题

### ISSUE THREAD

**Issue by ASFLY61** [iweizime/StepChanger#14]
魅族的Flyme系统，不能执行支付宝步数加载模块里的cp命令。无法将两个xml文件复制。但单独在终端执行可以成功。

**Comment by iweizime** [comment]
这个issue描述的很好，不想别人只丢过来一句加载不出来。然而，我也判断不出来有什么问题。。。
1. 检查一下有没有root权限
2. 检查一下路径/data/data/com.eg.android.AlipayGphone/shared_prefs/，/data/data/me.iweizi.stepchanger/shared_prefs/是不是符合

暂时没有想出其他的原因

**Comment by ASFLY61** [comment]
root权限是有的，路径也应该没问题。我特地刷了LineageOS 14.1,cp命令完美执行。可以加载出步数。

**Comment by iweizime** [comment]
这我就不知道了，很神奇

**Comment by wjinlong** [comment]
终于知道我的支付宝为啥也不行了，大概我是MIUI把

**Comment by wjinlong** [comment]
终于知道我的支付宝为啥也不行了，大概我是MIUI吧

**Comment by wjinlong** [comment]
可以用其他指令代替cp试试吧。
http://blog.csdn.net/fengye810130/article/details/9225783

**Comment by ASFLY61** [comment]
今天又看了下，发现Flyme系统不能执行chomd o+rw这种命令，会提示Bad mode。但可以执行busybox chomd o+rw。看了下你的代码，qq运动修改的时候，会复制key,应该cp命令没问题。之前qq 微信都是我手动加的权限，到软件里执行的时候，可以成功。但支付宝的，我手动给权限后，依旧会卡在chomd命令那，进su看日志，就提示Bad mode。

**Comment by ASFLY61** [comment]
我又看了下，是因为Flyme系统不能执行chomd o+rw这种命令，微信 qq我都是手动给权限，到软件里会成功加载。但支付宝不行，手动给权限后，但软件里加载，会卡在chomd命令那里，导致后面的cp命令执行不来。你的问题在哪里？解决了没？

**Comment by iweizime** [comment]
我自己的就是MIUI 9.2啊，没问题的，只是支付宝的服务器端校验比较严格，改的太多会失败。如果是命令的问题，你自己改一下相应的命令，编译一下吧。

**Comment by ASFLY61** [comment]
开发者大大，我不会安卓开发，也不懂咋弄。目前差不多觉得是命令问题，能否帮助改下命令，重新编译下呢？

**Comment by wjinlong** [comment]
@iweizime 同MIUI9，我支付宝是加载不出来，也不知道什么原因

**Comment by iweizime** [comment]
[release.zip](https://github.com/iweizime/StepChanger/files/1662664/release.zip)
你试一下这个，把chmod改成了busybox chmod @ @ASFLY61

**Comment by ASFLY61** [comment]
@iweizime cp命令还是不执行。busybox chmod在su里到是不显示Bad mode。但还是无法将两个xml文件复制。

**Comment by iweizime** [comment]
这个。。。难道要改成busybox cp ??? @wjinlong

**Comment by ASFLY61** [comment]
@iweizime  我也搞不清楚了，明明在终端可以完美执行cp命令。但在软件中就不行。那不行就把cp命令也用busybox里的试下吧。还是希望开发者大大可以帮忙编译一下。谢谢啦！

**Comment by ttimasdf** [comment]
cp文件会造成selinux报错
```
02-09 09:02:33.071  7303  7303 W SharedPreferenc: type=1400 audit(0.0:168): avc: denied { open } for path="/data/data/me.iweizi.stepchanger/shared_prefs/NewPedoMeter.xml" dev="dm-0" ino=308902 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:app_data_file:s0 tclass=file permissive=0
```
得在程序里手动createFile然后cat进去。
