### ISSUE TITLE
支付宝问题

### ISSUE THREAD

**Issue by HuiNIMA** [iweizime/StepChanger#15]
支付宝更新了10.1.15版本后加载不了步数，加载步数的弹窗一闪而过，加载不了
不知道是支付宝的问题还是MIUI的问题

**Comment by ASFLY61** [comment]
夸克浏览器：访问剪切板,内容为 可以看看/data/data/me.iweizi.stepchanger/shared_prefs下是否有NewPedoMeter_private.xml和NewPedoMeter.xml两个文件

**Comment by HuiNIMA** [comment]
两个文件都有的

**Comment by Testlyy** [comment]
支付宝10.1.15版本，提示获取读取存储权限后就没反应，加载不到数据，目录下面没有文件/data/data/me.iweizi.stepchanger/shared_prefs，支付宝有启动过获取到运动步数了，然后杀掉进程才启动步数修改器的，手机小米5 安卓7.0

**Comment by olympicjun** [comment]
将目录下面没有文件/data/data/me.iweizi.stepchanger/shared_prefs删除，重新加载就可以了。原文件中有一个steps -22540的数据，不是是否由此引起

**Comment by ASFLY61** [comment]
@olympicjun   我的删了还是不行。依旧加载不出来，不论哪个支付宝版本都不行。

**Comment by ttimasdf** [comment]
问题在于，这两个文件现在chmod以后还是不可读。
```
OnePlus3:/data/data/com.eg.android.AlipayGphone/shared_prefs # ls -l NewPedoMeter*
-rw-rw-rw- 1 u0_a107 u0_a107 441 2018-02-08 07:25 NewPedoMeter.xml
-rw-rw-rw- 1 u0_a107 u0_a107 331 2018-02-08 07:25 NewPedoMeter_private.xml
OnePlus3:/data/data/com.eg.android.AlipayGphone/shared_prefs # ^D
OnePlus3:/ $ cat /data/data/com.eg.android.AlipayGphone/shared_prefs/NewPedoMeter.xml
/system/bin/sh: cat: /data/data/com.eg.android.AlipayGphone/shared_prefs/NewPedoMeter.xml: Permission denied
```

**Comment by iweizime** [comment]
现在我自己的手机上支付宝也改不了了，现在没时间，等过两天放了假搞一下

**Comment by ttimasdf** [comment]
似乎遇到了算法更新。稍微修正了一下现在能正常读写文件。但是发现现在会检查NewPedoMeter_private.xml中的读数是否为负数了。所以 `newLastRecord.setSteps((int) (sensorStep - stepDiff));` 这一句不奏效了。

**Comment by iweizime** [comment]
OK, 跟我想的差不多，就是把cat命令也用root权限执行。当初想的是只用root权限执行chmod，普通权限执行cat，尽量减少root权限的申请，但后来发现sharedpreferences文件的权限每次都会被改。 @ttimasdf
