### ISSUE TITLE
6.0 flyme 修改无效

### ISSUE THREAD

**Issue by zhuxiucai** [iweizime/StepChanger#2]
一加3t，刷了flyme 6
android6.0
root
能load，但点击修改，再load，数值不变。即没有写入成功。
需要我补充什么信息吗？感谢！

**Comment by iweizime** [comment]
微信、QQ、支付宝都不行？

**Comment by zhuxiucai** [comment]
![wechatimg7](https://user-images.githubusercontent.com/10626025/30752708-c79fcf72-9f82-11e7-896e-1926175a5526.jpeg)
![wechatimg8](https://user-images.githubusercontent.com/10626025/30752711-c874404a-9f82-11e7-9859-3c7ee5566bde.jpeg)
![wechatimg9](https://user-images.githubusercontent.com/10626025/30752709-c7c2c784-9f82-11e7-89f0-081ca27525ec.jpeg)
微信可以加载到，但不能保存。
支付宝和QQ加载都不行。显示了获取权限，su也记录了授予权限。
其他app授予root权限，功能无异常。

**Comment by iweizime** [comment]
软件的计步功能开了吗？你看一下root授权的日志，我觉得有可能计步功能没开，所以没有对应的文件

**Comment by iweizime** [comment]
还有就是这个软件需要KILL_BACKGROUND_PROCESSES这个权限，不知道你给了这个权限没有

**Comment by zhuxiucai** [comment]
检查了一下root日志，发现 微信计步修改，并没有触发root，故没有root日志。微信计步功能是开了。支付宝和qq触发了root。不过我关注使用是微信，这里就不贴截图了。
值得注意的是，关于你提到的这个杀进程权限。我尝试pm给予权限，失败。而微信点击保存步数，也确实没有杀掉微信进程（在7.1的一加氢系统我使用成功过，知道会杀）。
这边不知还可能哪里有问题？

**Comment by iweizime** [comment]
微信和QQ用的是文件来保存数据，支付宝用的SharedPreferences，具体参考[wiki](https://github.com/iweizime/StepChanger/wiki)，所以微信和QQ只需要一次root，每次开支付宝之后都要root。微信没有root日志也正常。还有就是加载，改步数，保存之后，再加载确实还是原来的那个，这不算是bug，加载是以上传结果为准的，保存的是将要上传的数据。你保存了之后，打开一下微信运动步数排行那个页面，正常的话应该发现改成功了，再回来加载就回是新的步数。

**Comment by zhuxiucai** [comment]
非常感谢，最终通过 手动杀微信进程，改数字，重启微信，成功。
所以看起来根源是没把进程杀掉😳
