### ISSUE TITLE
Building failed with Exception thrown at CryptorUnitTest

### ISSUE THREAD

**Issue by aeroxy** [iweizime/StepChanger#22]
> > Task :app:testDebugUnitTest
> 
> me.iweizi.stepchanger.CryptorUnitTest > main FAILED
>     java.io.FileNotFoundException at CryptorUnitTest.java:29
> 
> me.iweizi.stepchanger.CryptorUnitTest > testDecrypt FAILED
>     java.io.FileNotFoundException at CryptorUnitTest.java:29
> 
> 4 tests completed, 2 failed

**Comment by aeroxy** [comment]
Probably cuz I am using a mac:

> RandomAccessFile file = new RandomAccessFile("C:\\Xiaomi\\XiaoMiFlash\\Source\\ThirdParty\\Google\\Android\\step.info", "r");

**Comment by iweizime** [comment]
you can remove the test code and build again. file "C:\Xiaomi\XiaoMiFlash\Source\ThirdParty\Google\Android\step.info" is copied from my cellphone.
