### ISSUE TITLE
小米 mi note lte android4.4.4ktu84p，apk安装格式解析错误

### ISSUE THREAD

**Issue by xtuyaowu** [iweizime/StepChanger#23]
求助，谢谢！

**Comment by iweizime** [comment]
[StepChanger-release.zip](https://github.com/iweizime/StepChanger/files/1766189/StepChanger-release.zip)
试试这个，可能是签名的问题

**Comment by xtuyaowu** [comment]
收到，谢谢，方便加个好友么？qq:1840658279

**Comment by xtuyaowu** [comment]
还是解析错误！

**Comment by iweizime** [comment]
可能是你的系统版本太老了。。。。
