### ISSUE TITLE
能不能release安装包？

### ISSUE THREAD

**Issue by junolym** [iweizime/StepChanger#29]
rt，不想装Android studio啊，卸载好久了

**Comment by Jerry981028** [comment]
https://androidfilehost.com/?fid=1322778262903986033
60164cdf4b216fe56997a2818dc7624faf3ed77b
Signed with my own key.

**Comment by wtw123123** [comment]
怎么安装啊😊头大

**Comment by junolym** [comment]
@wtw123123  上面那个老哥编译的可以用，我自己没编译出来，一个文件获取不到500了

**Comment by wtw123123** [comment]
链接挂了😂来晚了

**Comment by junolym** [comment]
没挂啊，我刚试了

**Comment by cheese-p** [comment]
> https://androidfilehost.com/?fid=1322778262903986033
> [60164cd](https://github.com/iweizime/StepChanger/commit/60164cdf4b216fe56997a2818dc7624faf3ed77b)
> Signed with my own key.

下不了啊

**Comment by junolym** [comment]
https://drive.google.com/open?id=1Ci1wsboFhhT7Crg6jPa-OKwHmetkdc0o
