### ISSUE TITLE
你好亲测安卓版可用，有ios版本么？

### ISSUE THREAD

**Issue by renqiang06** [iweizime/StepChanger#4]
1.安卓版可用，亲测，赞一个。
2.安卓版能设置一个目标值，然后定时上传渐变上升的步数直至目标值么？
3.希望能出一个ios版本。
再次感谢作者啦

**Comment by iweizime** [comment]
2. 应该是可以的实现的，就相当于手动改多次了，你可以自己在源码的基础上改一下，我就不改了
3. ios的我无能为力

**Comment by iweizime** [comment]
2. 对于支付宝这种平时是关闭状态的应用，其实无所谓逐步了，它本来也是一下子变很多

**Comment by renqiang06** [comment]
好的，👌非常感谢。
冒昧问一句，你现在还在交大上学么？

**Comment by iweizime** [comment]
在，有什么事吗

**Comment by renqiang06** [comment]
没事哈。在校学生，那就更厉害了啊
