### ISSUE TITLE
QQ步数加载失败

### ISSUE THREAD

**Issue by HuiNIMA** [iweizime/StepChanger#5]
QQ的步数加载不出来，点加载没反应

**Comment by iweizime** [comment]
试了一下，我自己的手机上也没反应，我看一下

**Comment by iweizime** [comment]
手机QQ更新了7.2.5版本，在这个版本中改变了步数保存的方法，换成7.2.0或以前的版本就可以了，至于怎么支持7.2.5，这个暂时没研究

**Comment by HuiNIMA** [comment]
好的，QQ的问题解决了，还有就是支付宝的步数改了不更新。。。

**Comment by iweizime** [comment]
支付宝可以的，你按照步骤做

**Comment by HuiNIMA** [comment]
那难道是定制ROM（MIUI）的问题？我的依旧不行，现在用着你那个微信步数修改

**Comment by HuiNIMA** [comment]
嗯，支付宝可以了，只是一次不能加太多，刷新不出来的话就多试几次就行

**Comment by wyl6551305** [comment]
希望大佬早点研究出QQ7.2.5保存步数的方法。

**Comment by iweizime** [comment]
@wyl6551305 7.2.5版本我看过了，不使用加密了，而是加了签名，拿不到密钥，伪造不了签名

**Comment by wyl6551305** [comment]
大佬拿不到密钥那是不是等于无解了，永远相信美好的事情即将发生。

**Comment by wyl6551305** [comment]
怪不得今天我看了一下/data/data/com.tencent.mobileqq/files/step.info这个文件没加密，原来改签名了，改了半天权限也没读取到，唉。

**Comment by iweizime** [comment]
对，同目录下面还有一个stepSign.info，这个是签名文件，密钥在AndroidKeystore，要么拿到密钥，要么只能修改apk去掉校验了

**Comment by wyl6551305** [comment]
可不可以做个XP模块hook掉校检呢？

**Comment by iweizime** [comment]
那直接用XP模块改步数不更直接。。。。

**Comment by wyl6551305** [comment]
目前的XP模块实现的方式不是很喜欢。

**Comment by iweizime** [comment]
等安卓7.x的稳定xposed出来可以做一下，应该快了

**Comment by iweizime** [comment]
你也可以帮着查一下root权限能不能拿到密钥，我目前没查到

**Comment by wyl6551305** [comment]
用过很多运动类修改软件，只有作者开发的这个运动软件让我眼前一亮，root就能修改从而降低了使用门槛，虽然我平时偶尔用一下这些修改软件，但突然失效了总觉得手机缺少了点什么。

**Comment by iweizime** [comment]
我之前也是觉得别的改步数的方法不够直接。不知道为什么QQ就改了方法。。。

**Comment by wyl6551305** [comment]
虽然作者提供的这种方法简单直接了点，但是总是有办法写死的。目前修改手机传感器速度的方法依然实用，但毕竟每个人手机系统和传感器型号不一样，数据走的太快了一不小心就会被封掉数据。

**Comment by xmlxin** [comment]
支付宝的运动数据加载不出来了

**Comment by HuiNIMA** [comment]
支付宝可以的

**Comment by xmlxin** [comment]
在红米note4x手机上授予root权限  加载支付宝数据加载不出来，微信的可以

**Comment by xmlxin** [comment]
提示正在获取读写权限 一闪而过

**Comment by qq45119626FangZhi** [comment]
支付宝点击加载，不出来数据，对话框一闪而过，，点保存提示先加载。qq点击加载什么提示也没有，
