### ISSUE TITLE
支付宝 失效了啦

### ISSUE THREAD

**Issue by leftshine** [iweizime/StepChanger#7]
保存之后 读取出来的数据有问题 支付宝这边补数毫无变化

**Comment by iweizime** [comment]
按照流程，多试两次，可以的。不要改的太快

**Comment by HuiNIMA** [comment]
支付宝好像只有每天第一次改有用

**Comment by leftshine** [comment]
昨天更新了qq之后，QQ也不能用了，然后无论怎么降级都没有效果了，不知道qq做了啥，很是诡异
