### ISSUE TITLE
支付宝修改不了

### ISSUE THREAD

**Issue by wang25164** [iweizime/StepChanger#8]
第一次加载数假设是a，下一次点击加载输入数字b，但是这时加载的数字就还是会变成a

**Comment by iweizime** [comment]
按照1，清空缓存。2，加载。3，更改。4，保存。这个步骤，我这边可以的。注意不要改的太快

**Comment by iweizime** [comment]
还有就是保存之后，打开支付宝查看新的步数。不要在这个应用里再按加载，这个加载出来的确实是之前的步数。

**Comment by ttimasdf** [comment]
保存以后再加载步数不会变，这个其实是安卓系统的bug啦～ 3a328f64aa81c997d79c9e0765987250575ce0ff 也顺便修复了这个
